# Generated by Django 3.0.4 on 2020-03-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDB_app', '0003_auto_20200328_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='images/img.jpeg', height_field=400, upload_to='', width_field=400),
        ),
    ]
