# Generated by Django 3.0.4 on 2020-03-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDB_app', '0004_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='images/img.jpeg', upload_to='images/'),
        ),
    ]
