# Generated by Django 3.0.4 on 2020-03-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDB_app', '0006_auto_20200328_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='images/img.jpeg', upload_to='images/'),
        ),
    ]
