# Generated by Django 3.0.4 on 2020-03-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDB_app', '0007_auto_20200328_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='static/images/img.jpeg', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='static/images/img.jpeg', upload_to='static/images/'),
        ),
    ]
