# Generated by Django 3.0.4 on 2020-03-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDB_app', '0009_auto_20200329_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='gallery/img.jpeg', upload_to='gallery'),
        ),
    ]
