# Generated by Django 3.0.4 on 2020-03-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDB_app', '0011_auto_20200330_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='formDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='gallery/img.jpeg', upload_to='gallery'),
        ),
    ]
