# Generated by Django 3.0.4 on 2020-04-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDB_app', '0012_auto_20200330_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formDB',
        ),
    ]
