# Generated by Django 3.0.4 on 2020-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDB_app', '0015_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='photo',
            field=models.ImageField(blank=True, default='gallery/img.jpeg', upload_to='gallery'),
        ),
    ]
